title: Robust Robotic Pouring using Audition and Haptics
description: Hongzhuo Liang, Chuangchuang Zhou, Shuang Li, Xiaojian Ma, Norman Hendrich, Timo Gerkmann, Fuchun Sun, Jianwei Zhang
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: false